### ISSUE TITLE
Databass Setting (khada)

### ISSUE THREAD

**Issue by hyunkang-lee** [404NOTFOUND-Team1/SemiProject404NotFound#1]
- [x]  이벤트 테이블 만들기
- [x]  이미지 테이블 만들기
- [x]  옵션 테이블 만들기
- [x]  카테고리 테이블 만들기
- [x]  장바구니 테이블 만들기
- [x]  상품 입고 테이블 만들기
- [x]  상품 테이블 만들기
- [x]  테스트 데이터 넣기

**Comment by hyunkang-lee** [comment]
완료!

**Comment by sooyeun-kim** [comment]
다 됐으니 close!
